name: Publish Docker Image

on:
  release:
    types: [published]
    
jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: registry.hub.docker.com

      - name: Build :latest
        if: success()
        run: docker build --file build/Dockerfile -t registry.hub.docker.com/${{ secrets.DOCKER_USERNAME }}/dsv-k8s-test:latest .
        
      - name: Push to docker hub :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push registry.hub.docker.com/${{ secrets.DOCKER_USERNAME }}/dsv-k8s-test:latest
